/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => StandupKitPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// editor-extension.ts
var import_view = require("@codemirror/view");
var import_language = require("@codemirror/language");
function jokeSyntaxDecoration() {
  return import_view.ViewPlugin.fromClass(class {
    constructor(view) {
      this.decorations = this.buildDecorations(view);
    }
    update(update) {
      if (update.docChanged || update.viewportChanged) {
        this.decorations = this.buildDecorations(update.view);
      }
    }
    buildDecorations(view) {
      const builder = [];
      for (const { from, to } of view.visibleRanges) {
        (0, import_language.syntaxTree)(view.state).iterate({
          from,
          to,
          enter: (node) => {
            const text = view.state.doc.sliceString(node.from, node.to);
            if (node.name === "line") {
              if (text.startsWith("^")) {
                builder.push(import_view.Decoration.line({ class: "cm-joke-punchline" }).range(node.from));
              } else if (text.startsWith("+++")) {
                builder.push(import_view.Decoration.line({ class: "cm-joke-tag cm-joke-tag-3" }).range(node.from));
              } else if (text.startsWith("++")) {
                builder.push(import_view.Decoration.line({ class: "cm-joke-tag cm-joke-tag-2" }).range(node.from));
              } else if (text.startsWith("+")) {
                builder.push(import_view.Decoration.line({ class: "cm-joke-tag" }).range(node.from));
              } else if (text.startsWith(">")) {
                builder.push(import_view.Decoration.line({ class: "cm-performance-note" }).range(node.from));
              } else if (text.startsWith("~")) {
                builder.push(import_view.Decoration.line({ class: "cm-joke-boneyard" }).range(node.from));
              }
            }
          }
        });
      }
      return import_view.Decoration.set(builder);
    }
  }, {
    decorations: (v) => v.decorations
  });
}

// rehearsal-view.ts
var import_obsidian = require("obsidian");
var REHEARSAL_VIEW_TYPE = "rehearsal-view";
var RehearsalView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.jokes = [];
    this.currentJokeIndex = -1;
  }
  getViewType() {
    return REHEARSAL_VIEW_TYPE;
  }
  getDisplayText() {
    return "Rehearsal";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.createEl("h4", { text: "Rehearsal" });
    const masterTimeEl = container.createEl("div", { text: "Master Time: 0s" });
    const lapTimeEl = container.createEl("div", { text: "Lap Time: 0s" });
    const currentJokeEl = container.createEl("div");
    const nextButton = container.createEl("button", { text: "Start" });
    nextButton.onClickEvent(async () => {
      if (this.currentJokeIndex === -1) {
        this.startRehearsal();
        nextButton.setText("Next");
      } else if (this.currentJokeIndex < this.jokes.length - 1) {
        this.nextJoke();
      } else {
        this.finishRehearsal();
        nextButton.setText("Start");
      }
    });
    this.masterTimerInterval = setInterval(() => {
      if (this.masterTimer) {
        this.masterTimer++;
        masterTimeEl.setText(`Master Time: ${this.masterTimer}s`);
      }
    }, 1e3);
    this.lapTimerInterval = setInterval(() => {
      if (this.lapTimer) {
        this.lapTimer++;
        lapTimeEl.setText(`Lap Time: ${this.lapTimer}s`);
      }
    }, 1e3);
  }
  async onClose() {
    clearInterval(this.masterTimerInterval);
    clearInterval(this.lapTimerInterval);
  }
  async startRehearsal() {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      const fileCache = this.app.metadataCache.getFileCache(activeFile);
      if (fileCache && fileCache.embeds) {
        for (const embed of fileCache.embeds) {
          const jokeFile = this.app.metadataCache.getFirstLinkpathDest(embed.link, activeFile.path);
          if (jokeFile instanceof import_obsidian.TFile) {
            this.jokes.push(jokeFile);
          }
        }
      }
    }
    this.masterTimer = 0;
    this.lapTimer = 0;
    this.currentJokeIndex = 0;
    this.loadJoke();
  }
  async nextJoke() {
    this.recordLap();
    this.lapTimer = 0;
    this.currentJokeIndex++;
    this.loadJoke();
  }
  async finishRehearsal() {
    this.recordLap();
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      await this.app.fileManager.processFrontMatter(activeFile, (frontmatter) => {
        frontmatter.actual_duration = import_obsidian.moment.utc(this.masterTimer * 1e3).format("m[m] ss[s]");
      });
    }
    this.currentJokeIndex = -1;
    this.masterTimer = 0;
    this.lapTimer = 0;
  }
  async loadJoke() {
    const jokeFile = this.jokes[this.currentJokeIndex];
    const content = await this.app.vault.read(jokeFile);
    const jokeText = content.split("---").slice(2).join("---").trim();
    const currentJokeEl = this.containerEl.querySelector("div:nth-child(3)");
    if (currentJokeEl) {
      currentJokeEl.setText(jokeText);
    }
  }
  async recordLap() {
    const jokeFile = this.jokes[this.currentJokeIndex];
    await this.app.fileManager.processFrontMatter(jokeFile, (frontmatter) => {
      if (!frontmatter.run_times) {
        frontmatter.run_times = [];
      }
      frontmatter.run_times.push({
        [(0, import_obsidian.moment)().format("YYYY-MM-DD")]: `${this.lapTimer}s`
      });
    });
  }
};

// main.ts
var StandupKitPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.editorExtension = [];
  }
  async onload() {
    console.log("Loading Standup Kit Plugin");
    this.registerEditorExtension(this.editorExtension);
    this.updateEditorExtension();
    this.statusBarItemEl = this.addStatusBarItem();
    this.registerEvent(this.app.workspace.on("file-open", this.updateStatus.bind(this)));
    this.registerEvent(this.app.metadataCache.on("changed", this.updateStatus.bind(this)));
    this.registerView(REHEARSAL_VIEW_TYPE, (leaf) => new RehearsalView(leaf));
    this.addRibbonIcon("microphone", "Rehearse Set", () => {
      this.activateView();
    });
  }
  onunload() {
    console.log("Unloading Standup Kit Plugin");
  }
  updateEditorExtension() {
    this.editorExtension.length = 0;
    this.editorExtension.push(jokeSyntaxDecoration());
    this.app.workspace.updateOptions();
  }
  async activateView() {
    this.app.workspace.detachLeavesOfType(REHEARSAL_VIEW_TYPE);
    const rightLeaf = this.app.workspace.getRightLeaf(false);
    if (rightLeaf) {
      await rightLeaf.setViewState({
        type: REHEARSAL_VIEW_TYPE,
        active: true
      });
    }
    this.app.workspace.revealLeaf(
      this.app.workspace.getLeavesOfType(REHEARSAL_VIEW_TYPE)[0]
    );
  }
  async updateStatus() {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      const fileCache = this.app.metadataCache.getFileCache(activeFile);
      if (fileCache && fileCache.frontmatter && fileCache.frontmatter.duration) {
        const targetDuration = import_obsidian2.moment.duration(fileCache.frontmatter.duration).asSeconds();
        let totalDuration = 0;
        if (fileCache.embeds) {
          for (const embed of fileCache.embeds) {
            const jokeFile = this.app.metadataCache.getFirstLinkpathDest(embed.link, activeFile.path);
            if (jokeFile instanceof import_obsidian2.TFile) {
              const jokeCache = this.app.metadataCache.getFileCache(jokeFile);
              if (jokeCache && jokeCache.frontmatter && jokeCache.frontmatter.est_duration) {
                totalDuration += import_obsidian2.moment.duration(jokeCache.frontmatter.est_duration).asSeconds();
              }
            }
          }
        }
        const difference = totalDuration - targetDuration;
        const underOver = difference > 0 ? "over" : "under";
        const diffText = import_obsidian2.moment.utc(Math.abs(difference) * 1e3).format("m[m] ss[s]");
        const totalText = import_obsidian2.moment.utc(totalDuration * 1e3).format("m[m] ss[s]");
        const targetText = import_obsidian2.moment.utc(targetDuration * 1e3).format("m[m] ss[s]");
        this.statusBarItemEl.setText(`Set Time: ${totalText} / ${targetText} (${diffText} ${underOver})`);
      } else {
        this.statusBarItemEl.setText("");
      }
    } else {
      this.statusBarItemEl.setText("");
    }
  }
};
